aws_region        = "eu-west-1"
availability_zone = "eu-west-1a"
aws_account       = "624368621157"
environment       = "ksone"
instance_type     = "t2.medium"
ssh_key_name      = "ksone"
ip_master         = "10.0.0.137"